In [1]:
import copy
import datetime as dt
from datetime import datetime
import importlib  # needed so that we can reload packages
import logging
import os
import pathlib
import sys
import time
import warnings
from typing import Union, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# --- Make notebooks/ importable from any sector subfolder ---
import os, sys, pathlib
_NB_PARENT = pathlib.Path(os.getcwd()).parent  # notebooks/<sector>/ -> notebooks/
if str(_NB_PARENT) not in sys.path:
    sys.path.insert(0, str(_NB_PARENT))

from utils.logger_utils import setup_clean_logger, mute_external_loggers

# SISEPUEDE imports
from sisepuede.manager.sisepuede_examples import SISEPUEDEExamples
from sisepuede.manager.sisepuede_file_structure import SISEPUEDEFileStructure
import sisepuede.core.support_classes as sc
import sisepuede.utilities._plotting as spu
import sisepuede.utilities._toolbox as sf
import sisepuede.core.attribute_table as att
import sisepuede.manager.sisepuede_examples as sxl
import sisepuede.manager.sisepuede_file_structure as sfs
import sisepuede.manager.sisepuede_models as sm
import sisepuede.visualization.plots as svp



# --- Runtime configuration ---
warnings.filterwarnings("ignore")

# Set up a clean logger for your notebook
logger = setup_clean_logger("notebook", logging.INFO)
logger.info("Notebook started successfully.")

# Mute logs from sisepuede to avoid duplication
mute_external_loggers(["sisepuede"])
# run this on the terminal /opt/anaconda3/envs/ssp_libya_env_2/bin/python -m pip install "setuptools>=60,<70"

2026-09-17 17:27:13,928 - INFO - Notebook started successfully.

In [2]:
%load_ext autoreload
%autoreload 2

### Initial Set up

Make sure to edit the config yaml under ssp_modeling/config_files/config.yaml

You can also create a new config yaml

In [3]:
# Set up dir paths

CURR_DIR_PATH = pathlib.Path(os.getcwd())
NOTEBOOKS_DIR_PATH = CURR_DIR_PATH.parent  # notebooks/<sector>/ -> notebooks/
SSP_MODELING_DIR_PATH = NOTEBOOKS_DIR_PATH.parent
PROJECT_DIR_PATH = SSP_MODELING_DIR_PATH.parent
DATA_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("input_data")
RUN_OUTPUT_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("ssp_run_output")
SCENARIO_MAPPING_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("scenario_mapping")
CONFIG_DIR_PATH = NOTEBOOKS_DIR_PATH.joinpath("config_files")
TRANSFORMATIONS_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("transformations")
MISC_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("misc")
STRATEGIES_DEFINITIONS_FILE_PATH = TRANSFORMATIONS_DIR_PATH.joinpath("strategy_definitions.csv")
STRATEGY_MAPPING_FILE_PATH = MISC_DIR_PATH.joinpath("strategy_mapping.yaml")

In [4]:
from ssp_transformations_handler.GeneralUtils import GeneralUtils
from ssp_transformations_handler.TransformationUtils import TransformationYamlProcessor, StrategyCSVHandler

# Initialize general utilities
g_utils = GeneralUtils()

In [5]:
# Load config file, double check your parameters are correct

YAML_FILE_PATH = os.path.join(CONFIG_DIR_PATH, "config.yaml")
config_params = g_utils.read_yaml(YAML_FILE_PATH)

country_name = config_params['country_name']
ssp_input_file_name = config_params['ssp_input_file_name']
ssp_transformation_cw = config_params['ssp_transformation_cw']
energy_model_flag = config_params['energy_model_flag']
set_lndu_reallocation_factor_to_zero_flag = config_params['set_lndu_reallocation_factor_to_zero']
sim_end_year = config_params.get('sim_end_year', 2050)  # Default to 2050 if not specified

# Print config parameters
logger.info(f"Country name: {country_name}")
logger.info(f"SSP input file name: {ssp_input_file_name}")
logger.info(f"SSP transformation CW: {ssp_transformation_cw}")
logger.info(f"Energy model flag: {energy_model_flag}")
logger.info(f"Set lndu reallocation factor to zero flag: {set_lndu_reallocation_factor_to_zero_flag}")
logger.info(f"Simulation end year: {sim_end_year}")

2026-09-17 17:27:14,022 - INFO - Country name: morocco
2026-09-17 17:27:14,022 - INFO - SSP input file name: sisepuede_raw_input_morocco_fuels_inen_ippu_scoe_prodcal_BLD_DEMAND_UP.csv
2026-09-17 17:27:14,023 - INFO - SSP transformation CW: ssp_morocco_transformation_cw.xlsx
2026-09-17 17:27:14,023 - INFO - Energy model flag: True
2026-09-17 17:27:14,023 - INFO - Set lndu reallocation factor to zero flag: True
2026-09-17 17:27:14,023 - INFO - Simulation end year: 2050

In [6]:
def get_file_structure(
    y0: int = 2015,
    y1: int = sim_end_year,
) -> Tuple[sfs.SISEPUEDEFileStructure, att.AttributeTable]:
    """Get the SISEPUEDE File Structure and update the attribute table
        with new years.
    """
    # setup some SISEPUEDE variables and update time period
    file_struct = sfs.SISEPUEDEFileStructure(
        initialize_directories = False,
    )
 
    # get some keys
    key_time_period = file_struct.model_attributes.dim_time_period
    key_year = file_struct.model_attributes.field_dim_year
 
 
    ##  BUILD THE ATTRIBUTE AND UPDATE
 
    # setup the new attribute table
    years = np.arange(y0, y1 + 1, ).astype(int)
    attribute_time_period = att.AttributeTable(
        pd.DataFrame(
            {
                key_time_period: range(len(years)),
                key_year: years,
            }
        ),
        key_time_period,
    )
 
    # finally, update the ModelAttributes inside the file structure
    (
        file_struct
        .model_attributes
        .update_dimensional_attribute_table(
            attribute_time_period,
        )
    )
 
    # return the tuple
    out = (file_struct, attribute_time_period, )
 
    return out

In [7]:
# Set up SSP objects
INPUT_FILE_PATH = DATA_DIR_PATH.joinpath(ssp_input_file_name)

# model attributes and associated support classes
_EXAMPLES = sxl.SISEPUEDEExamples()
_FILE_STRUCTURE, _ATTRIBUTE_TABLE_TIME_PERIOD = get_file_structure(y1=sim_end_year)
matt = _FILE_STRUCTURE.model_attributes
regions = sc.Regions(matt, )
time_periods = sc.TimePeriods(matt, )

In [8]:
# setup models in case we need them
models = sm.SISEPUEDEModels(
    matt,
    allow_electricity_run = True,
    fp_julia = _FILE_STRUCTURE.dir_jl,
    fp_nemomod_reference_files = _FILE_STRUCTURE.dir_ref_nemo,
    initialize_julia = False, 
)

### Making sure our input file has the correct format and correct columns
We use an example df with the complete fields and correct format to make sure our file is in the right shape

In [9]:
##  BUILD BASE INPUTS
df_inputs_raw = pd.read_csv(INPUT_FILE_PATH)

# pull example data to fill in gaps
df_example_input = _EXAMPLES("input_data_frame")

In [10]:
# Double checking that our df is in the correct shape (Empty sets should be printed to make sure everything is Ok!)
g_utils.compare_dfs(df_example_input, df_inputs_raw)

Columns in df_example but not in df_input: {'frac_trns_fuelmix_water_borne_gasoline', 'frac_lndu_seasonal_wetland_shrublands', 'frac_lndu_seasonal_wetland_croplands', 'frac_lndu_seasonal_wetland_pastures', 'frac_lndu_seasonal_wetland_other', 'region', 'frac_frst_forest_conversions_available_for_fuelwood', 'frac_lndu_seasonal_wetland_grasslands'}
Columns in df_input but not in df_example: {'ef_fgtv_distribution_tonne_co2_per_m3_fuel_crude', 'frac_fgtv_capture_associated_gas_fuel_oil', 'frac_fgtv_capture_associated_gas_fuel_coal', 'ef_fgtv_distribution_tonne_ch4_per_m3_fuel_crude', 'iso_alpha_3', 'year', 'frac_fgtv_capture_associated_gas_fuel_crude'}

In [11]:
all_fields = matt.all_variable_fields_input
df_fiels = df_inputs_raw.columns.tolist()
missing_fields = list(set(all_fields) - set(df_fiels))
print("Missing fields in the input data frame:")
print(missing_fields)

Missing fields in the input data frame:
['frac_trns_fuelmix_water_borne_gasoline', 'frac_lndu_seasonal_wetland_shrublands', 'frac_lndu_seasonal_wetland_croplands', 'frac_lndu_seasonal_wetland_pastures', 'frac_lndu_seasonal_wetland_other', 'frac_frst_forest_conversions_available_for_fuelwood', 'frac_lndu_seasonal_wetland_grasslands']

In [12]:
# Ensure if time_period field exist
if 'time_period' not in df_inputs_raw.columns:
    logger.info("Adding 'time_period' column to df_inputs_raw")
    df_inputs_raw = df_inputs_raw.rename(columns={'period':'time_period'})
else:
    logger.info("'time_period' column already exists in df_inputs_raw")

2026-09-17 17:27:14,778 - INFO - 'time_period' column already exists in df_inputs_raw

In [13]:
# Fixes differences and makes sure that our df is in the correct format.
# Note: Edit this if you need more changes in your df

df_inputs_raw_complete = g_utils.add_missing_cols(df_example_input, df_inputs_raw.copy())
df_inputs_raw_complete.head()

,time_period,year,area_gnrl_country_ha,area_lndu_infimum_croplands_ha,area_lndu_infimum_flooded_ha,area_lndu_infimum_forests_mangroves_ha,area_lndu_infimum_forests_primary_ha,area_lndu_infimum_forests_secondary_ha,area_lndu_infimum_grasslands_ha,area_lndu_infimum_other_ha,...,yf_agrc_vegetables_and_vines_tonne_ha,yf_lndu_supremum_pastures_tonne_per_ha,region,frac_trns_fuelmix_water_borne_gasoline,frac_frst_forest_conversions_available_for_fuelwood,frac_lndu_seasonal_wetland_croplands,frac_lndu_seasonal_wetland_grasslands,frac_lndu_seasonal_wetland_other,frac_lndu_seasonal_wetland_pastures,frac_lndu_seasonal_wetland_shrublands
0,0,2015,44655000,-999,-999,-999,-999,-999,-999,-999,...,24.760000,92.81,costa_rica,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,2016,44655000,-999,-999,-999,-999,-999,-999,-999,...,25.570737,92.81,costa_rica,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,2017,44655000,-999,-999,-999,-999,-999,-999,-999,...,24.673359,92.81,costa_rica,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,2018,44655000,-999,-999,-999,-999,-999,-999,-999,...,25.327768,92.81,costa_rica,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,2019,44655000,-999,-999,-999,-999,-999,-999,-999,...,28.151940,92.81,costa_rica,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
# Double checking that our df is in the correct shape (Empty sets should be printed to make sure everything is Ok!)
g_utils.compare_dfs(df_example_input, df_inputs_raw_complete)

Columns in df_example but not in df_input: set()
Columns in df_input but not in df_example: {'ef_fgtv_distribution_tonne_co2_per_m3_fuel_crude', 'frac_fgtv_capture_associated_gas_fuel_oil', 'frac_fgtv_capture_associated_gas_fuel_coal', 'ef_fgtv_distribution_tonne_ch4_per_m3_fuel_crude', 'iso_alpha_3', 'year', 'frac_fgtv_capture_associated_gas_fuel_crude'}

In [15]:
df_inputs_raw_complete["region"].head()

0    costa_rica
1    costa_rica
2    costa_rica
3    costa_rica
4    costa_rica
Name: region, dtype: object

In [16]:
# Set region to country name
df_inputs_raw_complete['region'] = country_name
df_inputs_raw_complete['region'].head()

0    morocco
1    morocco
2    morocco
3    morocco
4    morocco
Name: region, dtype: object

In [17]:
# filter to match sim_end_year
print(f"min and max years in raw inputs before filtering: {df_inputs_raw_complete['year'].min()} to {df_inputs_raw_complete['year'].max()}")
df_inputs_raw_complete = df_inputs_raw_complete[df_inputs_raw_complete['year'] <= sim_end_year]
print(f"min and max years in raw inputs after filtering: {df_inputs_raw_complete['year'].min()} to {df_inputs_raw_complete['year'].max()}")

min and max years in raw inputs before filtering: 2015 to 2070
min and max years in raw inputs after filtering: 2015 to 2050

In [18]:
df_inputs_raw_complete[['ef_frst_sequestration_primary_kt_co2_ha','ef_frst_sequestration_secondary_kt_co2_ha','ef_frst_sequestration_young_secondary_kt_co2_ha']].head()

,ef_frst_sequestration_primary_kt_co2_ha,ef_frst_sequestration_secondary_kt_co2_ha,ef_frst_sequestration_young_secondary_kt_co2_ha
0,0.000025,0.000053,0.000103
1,0.000025,0.000053,0.000103
2,0.000025,0.000053,0.000103
3,0.000025,0.000053,0.000103
4,0.000025,0.000053,0.000103

In [19]:
df_inputs_raw_complete['frac_frst_forest_conversions_available_for_fuelwood']

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
21    0.0
22    0.0
23    0.0
24    0.0
25    0.0
26    0.0
27    0.0
28    0.0
29    0.0
30    0.0
31    0.0
32    0.0
33    0.0
34    0.0
35    0.0
Name: frac_frst_forest_conversions_available_for_fuelwood, dtype: float64

### Custom data modifications (in-memory on `df_inputs_raw_complete`)

Adjustments applied directly to the input dataframe BEFORE building the strategies. Each modification is documented with its rationale and IEA reference. **These are not changes to `df_input_1.csv` on disk** — they live in this notebook so the data source remains reproducible.

| Change | Variable | Value | Reason | Reference |
|---|---|---:|---|---|
| Add gas MSP for BAU | `nemomod_entc_frac_min_share_production_pp_gas` | 0.10 (all years) | df_input_1 has gas MSP = 0, so NemoMod never dispatches natural gas in BAU. Forcing 10% aligns with Morocco 2018 IEA actual (~10-12% gas in generation mix). | IEA Energy Statistics Morocco 2018-2023; ONEE annual reports |

In [20]:
# CUSTOM DATA MODIFICATIONS
# Apply gas MSP = 0.10 so BAU dispatches natural gas to match IEA Morocco mix
# (df_input_1.csv has gas MSP = 0, which causes NemoMod to never dispatch gas)

import numpy as np
_gas_msp_col = 'nemomod_entc_frac_min_share_production_pp_gas'
_gas_msp_target = 0.10

assert _gas_msp_col in df_inputs_raw_complete.columns, f'Column {_gas_msp_col} missing'
_before = df_inputs_raw_complete[_gas_msp_col].iloc[0]
df_inputs_raw_complete[_gas_msp_col] = _gas_msp_target
_after = df_inputs_raw_complete[_gas_msp_col].iloc[0]
print(f'gas MSP: {_before} -> {_after} (applied to all {len(df_inputs_raw_complete)} rows)')

# Verify total MSP per year stays below 1.0 (NemoMod needs headroom)
_mix_cols = [c for c in df_inputs_raw_complete.columns if c.startswith('nemomod_entc_frac_min_share_production_pp_')]
_sums = df_inputs_raw_complete[_mix_cols].sum(axis=1)
print(f'Sum of MSPs per year: min={_sums.min():.3f}, max={_sums.max():.3f}')
assert _sums.max() <= 1.0, 'MSP sum > 1.0 — would cause LP infeasibility'

# Show resulting MSP composition (non-zero only)
print('\nMSP composition after modification (sample at 2018):')
_row = df_inputs_raw_complete[df_inputs_raw_complete['time_period']==3].iloc[0]
for c in sorted(_mix_cols):
    v = _row[c]
    if v > 0:
        tech = c.replace('nemomod_entc_frac_min_share_production_pp_', '')
        print(f'  {tech:<20} {v:.4f}')
print(f'  {"SUM":<20} {sum(_row[c] for c in _mix_cols):.4f}')

gas MSP: 0.1 -> 0.1 (applied to all 36 rows)
Sum of MSPs per year: min=0.990, max=0.990

MSP composition after modification (sample at 2018):
  coal                 0.6200
  gas                  0.1000
  hydropower           0.0200
  nuclear              0.0100
  oil                  0.0500
  solar                0.0400
  wind                 0.1500
  SUM                  0.9900

#  Let's try building transformations using this

In [21]:
import sisepuede.transformers as trf
transformers = trf.transformers.Transformers(
    {},
    attr_time_period = _ATTRIBUTE_TABLE_TIME_PERIOD,
    df_input = df_inputs_raw_complete, # here you change the input table
)

##  Instantiate some transformations. Make sure to run this cell to create the transformations folder for the first time or if you wish to overwrite

In [22]:
# set an ouput path and instantiate
if not TRANSFORMATIONS_DIR_PATH.exists():
    trf.instantiate_default_strategy_directory(
        transformers,
        TRANSFORMATIONS_DIR_PATH,
    )
else:
    logger.info(f"Directory {TRANSFORMATIONS_DIR_PATH} already exists. Skipping instantiation.")

2026-09-17 17:27:15,262 - INFO - Directory /Users/fabianfuentes/git/ssp_morocco/ssp_modeling/transformations already exists. Skipping instantiation.

In [23]:
# then, you can load this back in after modifying (play around with it)
transformations = trf.Transformations(
    TRANSFORMATIONS_DIR_PATH,
    transformers = transformers,
)
tab = transformations.attribute_transformation.table

In [24]:
#  build the strategies -- will export to path
t0 = time.time()
strategies = trf.Strategies(
    transformations,
    export_path = "transformations",
    prebuild = True,
)

t_elapse = sf.get_time_elapsed(t0)
print(f"Strategies defined at {strategies.transformations.dir_init} initialized in {t_elapse} seconds")

Strategies defined at /Users/fabianfuentes/git/ssp_morocco/ssp_modeling/transformations initialized in 26.52 seconds

In [25]:
strategies.attribute_table

,strategy_id,strategy_code,strategy,description,transformation_specification,baseline_strategy_id
0,0,BASE,Strategy TX:BASE,NaN,TX:BASE,1
1,1000,AGRC:DEC_CH4_RICE,Singleton - Default Value - AGRC: Improve rice...,NaN,TX:AGRC:DEC_CH4_RICE,0
2,1001,AGRC:DEC_EXPORTS,Singleton - Default Value - AGRC: Decrease Exp...,NaN,TX:AGRC:DEC_EXPORTS,0
3,1002,AGRC:DEC_LOSSES_SUPPLY_CHAIN,Singleton - Default Value - AGRC: Reduce suppl...,NaN,TX:AGRC:DEC_LOSSES_SUPPLY_CHAIN,0
4,1003,AGRC:INC_CONSERVATION_AGRICULTURE,Singleton - Default Value - AGRC: Expand conse...,NaN,TX:AGRC:INC_CONSERVATION_AGRICULTURE,0
...,...,...,...,...,...,...
153,6084,WHIRLPOOL_PFLO_LEDS:TX:TRWW:INC_CAPTURE_BIOGAS...,Remove TX:TRWW:INC_CAPTURE_BIOGAS_STRATEGY_LED...,NaN,TX:AGRC:DEC_EXPORTS_STRATEGY_LEDS|TX:CCSQ:INC_...,0
154,6085,WHIRLPOOL_PFLO_LEDS:TX:TRWW:INC_COMPLIANCE_SEP...,Remove TX:TRWW:INC_COMPLIANCE_SEPTIC_STRATEGY_...,NaN,TX:AGRC:DEC_EXPORTS_STRATEGY_LEDS|TX:CCSQ:INC_...,0
155,6086,WHIRLPOOL_PFLO_LEDS:TX:WALI:INC_TREATMENT_INDU...,Remove TX:WALI:INC_TREATMENT_INDUSTRIAL_STRATE...,NaN,TX:AGRC:DEC_EXPORTS_STRATEGY_LEDS|TX:CCSQ:INC_...,0
156,6087,WHIRLPOOL_PFLO_LEDS:TX:WASO:DEC_CONSUMER_FOOD_...,Remove TX:WASO:DEC_CONSUMER_FOOD_WASTE_STRATEG...,NaN,TX:AGRC:DEC_EXPORTS_STRATEGY_LEDS|TX:CCSQ:INC_...,0
157,6088,WHIRLPOOL_PFLO_LEDS:TX:WASO:INC_ANAEROBIC_AND_...,Remove TX:WASO:INC_ANAEROBIC_AND_COMPOST_STRAT...,NaN,TX:AGRC:DEC_EXPORTS_STRATEGY_LEDS|TX:CCSQ:INC_...,0

In [26]:
strategies_to_run = [0, 6004]
strategies_to_run.extend(range(6047, 6089))
print(f"Strategies to run: {strategies_to_run}")

Strategies to run: [0, 6004, 6047, 6048, 6049, 6050, 6051, 6052, 6053, 6054, 6055, 6056, 6057, 6058, 6059, 6060, 6061, 6062, 6063, 6064, 6065, 6066, 6067, 6068, 6069, 6070, 6071, 6072, 6073, 6074, 6075, 6076, 6077, 6078, 6079, 6080, 6081, 6082, 6083, 6084, 6085, 6086, 6087, 6088]

##  Build our templates
- let's use the default variable groupings for LHS

In [27]:
# Building excel templates, make sure to include the strategies ids in the strategies attribute as well as the baseline (0)
df_vargroups = _EXAMPLES("variable_trajectory_group_specification")

strategies.build_strategies_to_templates(
    # df_trajgroup = df_vargroups,
    # include_simplex_group_as_trajgroup = True,
    strategies = strategies_to_run,
)

0

# Finally, load SISEPUEDE and run it

In [28]:
import sisepuede as si
# timestamp_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
ssp = si.SISEPUEDE(
    "calibrated",
    db_type = "csv",
    # id_str = f"sisepuede_run_2024-11-04T09:23:26.721580",
    initialize_as_dummy = not(energy_model_flag), # no connection to Julia is initialized if set to True
    regions = [country_name],
    strategies = strategies,
    # try_exogenous_xl_types_in_variable_specification = True,
    attribute_time_period=_ATTRIBUTE_TABLE_TIME_PERIOD
)

2026-09-17 17:28:54,668 - INFO - Successfully initialized SISEPUEDEFileStructure.
2026-09-17 17:28:54,669 - WARNING - Missing key dict_dimensional_keys: key time_series not found. Tables that rely on the time_series will not have index checking.
2026-09-17 17:28:54,670 - INFO - 	Setting export engine to 'csv'.
2026-09-17 17:28:54,670 - WARNING - No index fields defined. Index field values will not be checked when writing to tables.
2026-09-17 17:28:54,670 - INFO - Successfully instantiated table ANALYSIS_METADATA
2026-09-17 17:28:54,670 - WARNING - No index fields found in ATTRIBUTE_DESIGN. Initializing index fields.
2026-09-17 17:28:54,671 - INFO - Successfully instantiated table ATTRIBUTE_DESIGN
2026-09-17 17:28:54,671 - WARNING - No index fields found in ATTRIBUTE_LHC_SAMPLES_EXOGENOUS_UNCERTAINTIES. Initializing index fields.
2026-09-17 17:28:54,671 - INFO - Successfully instantiated table ATTRIBUTE_LHC_SAMPLES_EXOGENOUS_UNCERTAINTIES
2026-09-17 17:28:54,671 - WARNING - No index fields found in ATTRIBUTE_LHC_SAMPLES_LEVER_EFFECTS. Initializing index fields.
2026-09-17 17:28:54,671 - INFO - Successfully instantiated table ATTRIBUTE_LHC_SAMPLES_LEVER_EFFECTS
2026-09-17 17:28:54,671 - WARNING - No index fields found in ATTRIBUTE_PRIMARY. Initializing index fields.
2026-09-17 17:28:54,672 - INFO - Successfully instantiated table ATTRIBUTE_PRIMARY
2026-09-17 17:28:54,672 - WARNING - No index fields found in ATTRIBUTE_STRATEGY. Initializing index fields.
2026-09-17 17:28:54,672 - INFO - Successfully instantiated table ATTRIBUTE_STRATEGY
2026-09-17 17:28:54,672 - WARNING - No index fields found in ATTRIBUTE_TIME_PERIOD. Initializing index fields.
2026-09-17 17:28:54,672 - INFO - Successfully instantiated table ATTRIBUTE_TIME_PERIOD
2026-09-17 17:28:54,672 - WARNING - No index fields found in MODEL_BASE_INPUT_DATABASE. Initializing index fields.
2026-09-17 17:28:54,673 - INFO - Successfully instantiated table MODEL_BASE_INPUT_DATABASE
2026-09-17 17:28:54,673 - WARNING - No index fields found in MODEL_INPUT. Initializing index fields.
2026-09-17 17:28:54,673 - INFO - Successfully instantiated table MODEL_INPUT
2026-09-17 17:28:54,673 - WARNING - No index fields found in MODEL_OUTPUT. Initializing index fields.
2026-09-17 17:28:54,673 - INFO - Successfully instantiated table MODEL_OUTPUT
2026-09-17 17:28:54,673 - INFO - SISEPUEDEOutputDatabase successfully initialized IterativeDatabase.
2026-09-17 17:28:54,674 - INFO - Successfully initialized database with:
	type:	csv
	analysis id:	sisepuede_run_2026-09-17T17:28:54.353650
	fp_base_output:	/Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-09-17T17;28;54.353650/sisepuede_run_2026-09-17T17;28;54.353650_output_database
2026-09-17 17:28:54,674 - INFO - Running SISEPUEDE under template data mode 'calibrated'.
2026-09-17 17:28:54,674 - INFO - Initializing BaseInputDatabase
2026-09-17 17:28:57,966 - INFO - Initializing FutureTrajectories
2026-09-17 17:29:08,088 - INFO - Instantiating 1799 sampling units.
2026-09-17 17:29:08,099 - INFO - Iteration 0 complete.
2026-09-17 17:29:11,093 - INFO - Iteration 250 complete.
2026-09-17 17:29:12,680 - INFO - Iteration 500 complete.
2026-09-17 17:29:14,217 - INFO - Iteration 750 complete.
2026-09-17 17:29:15,808 - INFO - Iteration 1000 complete.
2026-09-17 17:29:17,326 - INFO - Iteration 1250 complete.
2026-09-17 17:29:18,930 - INFO - Iteration 1500 complete.
2026-09-17 17:29:20,446 - INFO - Iteration 1750 complete.
2026-09-17 17:29:20,752 - INFO - 	1799 sampling units complete in 12.66 seconds.
2026-09-17 17:29:20,758 - INFO - 	FutureTrajectories for 'morocco' complete.
2026-09-17 17:29:20,759 - INFO - Initializing LHSDesign
2026-09-17 17:29:20,760 - INFO - LHSDesign.fields_factors_l reset successful.
2026-09-17 17:29:20,760 - INFO - LHSDesign.fields_factors_x reset successful.
2026-09-17 17:29:20,776 - INFO - 	LHSDesign for region 'morocco' complete.
2026-09-17 17:29:20,777 - INFO - Generating primary keys (values of primary_id)...
2026-09-17 17:29:20,777 - INFO - Successfully initialized SISEPUEDEExperimentalManager.
2026-09-17 17:29:20,778 - INFO - Successfully initialized NemoMod temporary database path as /Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/tmp/nemomod_intermediate_database.sqlite.
2026-09-17 17:29:20,778 - INFO - Set Julia directory for modules and environment to '/Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/julia'.
2026-09-17 17:29:20,825 - INFO - Successfully read NemoMod input table data from /Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/ref/nemo_mod/AvailabilityFactor.csv
2026-09-17 17:29:20,828 - INFO - Successfully read NemoMod input table data from /Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/ref/nemo_mod/SpecifiedDemandProfile.csv
2026-09-17 17:29:20,878 - INFO - Importing Julia...

Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython

Precompiling NemoMod...
Info Given NemoMod was explicitly requested, output will be shown live
WARNING: Method definition parse_line(String) in module ConfParser at /Users/fabianfuentes/.julia/packages/ConfParser/b2fge/src/ConfParser.jl:95 overwritten in module NemoMod at /Users/fabianfuentes/.julia/packages/NemoMod/IIHRE/src/config_functions.jl:16.
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
   1255.9 ms  ? NemoMod
[ Info: Precompiling NemoMod [a3c327a0-d2f0-11e8-37fd-d12fd35c3c72]
WARNING: Method definition parse_line(String) in module ConfParser at /Users/fabianfuentes/.julia/packages/ConfParser/b2fge/src/ConfParser.jl:95 overwritten in module NemoMod at /Users/fabianfuentes/.julia/packages/NemoMod/IIHRE/src/config_functions.jl:16.
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
┌ Info: Skipping precompilation due to precompilable error. Importing NemoMod [a3c327a0-d2f0-11e8-37fd-d12fd35c3c72].
└   exception = Error when precompiling module, potentially caused by a __precompile__(false) declaration in the module.
2026-09-17 17:29:38,829 - INFO - Successfully initialized JuMP optimizer from solver module HiGHS.
2026-09-17 17:29:38,842 - INFO - Successfully initialized SISEPUEDEModels.
2026-09-17 17:29:38,849 - INFO - Table ANALYSIS_METADATA successfully written to /Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-09-17T17;28;54.353650/sisepuede_run_2026-09-17T17;28;54.353650_output_database/ANALYSIS_METADATA.csv.
2026-09-17 17:29:38,850 - INFO - Table ATTRIBUTE_DESIGN successfully written to /Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-09-17T17;28;54.353650/sisepuede_run_2026-09-17T17;28;54.353650_output_database/ATTRIBUTE_DESIGN.csv.
2026-09-17 17:29:38,852 - INFO - Table ATTRIBUTE_STRATEGY successfully written to /Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-09-17T17;28;54.353650/sisepuede_run_2026-09-17T17;28;54.353650_output_database/ATTRIBUTE_STRATEGY.csv.
2026-09-17 17:29:38,853 - INFO - Table ATTRIBUTE_TIME_PERIOD successfully written to /Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-09-17T17;28;54.353650/sisepuede_run_2026-09-17T17;28;54.353650_output_database/ATTRIBUTE_TIME_PERIOD.csv.
2026-09-17 17:29:40,019 - INFO - Table MODEL_BASE_INPUT_DATABASE successfully written to /Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-09-17T17;28;54.353650/sisepuede_run_2026-09-17T17;28;54.353650_output_database/MODEL_BASE_INPUT_DATABASE.csv.

In [29]:
not(energy_model_flag)

False

In [ ]:
# This runs the model, make sure you edit key_stretegy with the strategy ids you want to execute include baseline (0)
dict_scens = {
    ssp.key_design: [0],
    ssp.key_future: [0],
    ssp.key_strategy: strategies_to_run,
}

ssp.project_scenarios(
    dict_scens,
    save_inputs = True,
    include_electricity_in_energy = energy_model_flag,
    # dict_optimizer_attributes = {"user_bound_scale": -7, }
)

2026-09-17 17:29:40,105 - INFO -
***	STARTING REGION morocco	***

2026-09-17 17:29:41,119 - INFO - Trying run primary_id = 0 in region morocco
2026-09-17 17:29:41,119 - INFO - Running AFOLU model
2026-09-17 17:29:41,317 - INFO - AFOLU model run successfully completed
2026-09-17 17:29:41,317 - INFO - Running CircularEconomy model
2026-09-17 17:29:41,337 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:29:41,337 - INFO - Running IPPU model
2026-09-17 17:29:41,369 - INFO - IPPU model run successfully completed
2026-09-17 17:29:41,369 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:29:41,378 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:29:41,415 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:29:41,416 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)
2026-09-17 17:29:41,440 - INFO - 	Path to temporary NemoMod database '/Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/tmp/nemomod_intermediate_database.sqlite' not found. Creating...

2026-17-Sep 17:29:41.769 Opened SQLite database at /Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/tmp/nemomod_intermediate_database.sqlite.
2026-17-Sep 17:29:41.787 Added NEMO structure to SQLite database at /Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/tmp/nemomod_intermediate_database.sqlite.
2026-17-Sep 17:29:56.215 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.

2026-09-17 17:30:31,269 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:30:31,275 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:30:31,275 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:30:31,309 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:30:31,309 - INFO - Appending Socioeconomic outputs
2026-09-17 17:30:31,314 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:30:31,316 - INFO - Model run for primary_id = 0 successfully completed in 50.2 seconds (n_tries = 1).
2026-09-17 17:30:31,329 - INFO - Trying run primary_id = 73073 in region morocco
2026-09-17 17:30:31,329 - INFO - Running AFOLU model

2026-17-Sep 17:29:56.663 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:30:10.064 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:30:10.131 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:30:31.154 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:30:31,539 - INFO - AFOLU model run successfully completed
2026-09-17 17:30:31,539 - INFO - Running CircularEconomy model
2026-09-17 17:30:31,559 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:30:31,559 - INFO - Running IPPU model
2026-09-17 17:30:31,591 - INFO - IPPU model run successfully completed
2026-09-17 17:30:31,591 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:30:31,600 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:30:31,638 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:30:31,638 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:30:32.169 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:30:32.214 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:31:12,151 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:31:12,159 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:31:12,159 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:31:12,190 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:31:12,190 - INFO - Appending Socioeconomic outputs
2026-09-17 17:31:12,194 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:31:12,196 - INFO - Model run for primary_id = 73073 successfully completed in 40.87 seconds (n_tries = 1).
2026-09-17 17:31:12,206 - INFO - Trying run primary_id = 116116 in region morocco
2026-09-17 17:31:12,206 - INFO - Running AFOLU model

2026-17-Sep 17:30:38.588 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:30:38.640 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:31:12.071 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:31:12,414 - INFO - AFOLU model run successfully completed
2026-09-17 17:31:12,414 - INFO - Running CircularEconomy model
2026-09-17 17:31:12,435 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:31:12,435 - INFO - Running IPPU model
2026-09-17 17:31:12,469 - INFO - IPPU model run successfully completed
2026-09-17 17:31:12,469 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:31:12,479 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:31:12,519 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:31:12,519 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:31:13.051 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:31:13.095 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:31:53,002 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:31:53,009 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:31:53,009 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:31:53,054 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:31:53,054 - INFO - Appending Socioeconomic outputs
2026-09-17 17:31:53,059 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:31:53,060 - INFO - Model run for primary_id = 116116 successfully completed in 40.85 seconds (n_tries = 1).
2026-09-17 17:31:53,066 - INFO - Trying run primary_id = 117117 in region morocco
2026-09-17 17:31:53,067 - INFO - Running AFOLU model

2026-17-Sep 17:31:19.469 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:31:19.519 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:31:52.926 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:31:53,275 - INFO - AFOLU model run successfully completed
2026-09-17 17:31:53,275 - INFO - Running CircularEconomy model
2026-09-17 17:31:53,295 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:31:53,295 - INFO - Running IPPU model
2026-09-17 17:31:53,327 - INFO - IPPU model run successfully completed
2026-09-17 17:31:53,327 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:31:53,336 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:31:53,373 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:31:53,374 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:31:54.159 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:31:54.203 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:32:32,605 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:32:32,612 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:32:32,612 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:32:32,644 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:32:32,644 - INFO - Appending Socioeconomic outputs
2026-09-17 17:32:32,648 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:32:32,650 - INFO - Model run for primary_id = 117117 successfully completed in 39.58 seconds (n_tries = 1).
2026-09-17 17:32:32,656 - INFO - Trying run primary_id = 118118 in region morocco
2026-09-17 17:32:32,656 - INFO - Running AFOLU model

2026-17-Sep 17:32:00.649 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:32:00.701 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:32:32.532 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:32:32,867 - INFO - AFOLU model run successfully completed
2026-09-17 17:32:32,867 - INFO - Running CircularEconomy model
2026-09-17 17:32:32,887 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:32:32,888 - INFO - Running IPPU model
2026-09-17 17:32:32,919 - INFO - IPPU model run successfully completed
2026-09-17 17:32:32,920 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:32:32,928 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:32:32,967 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:32:32,967 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:32:33.512 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:32:33.557 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:33:26,618 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:33:26,624 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:33:26,625 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:33:26,657 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:33:26,658 - INFO - Appending Socioeconomic outputs
2026-09-17 17:33:26,662 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:33:26,664 - INFO - Model run for primary_id = 118118 successfully completed in 54.01 seconds (n_tries = 1).
2026-09-17 17:33:26,668 - INFO - Trying run primary_id = 119119 in region morocco
2026-09-17 17:33:26,668 - INFO - Running AFOLU model

2026-17-Sep 17:32:40.024 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:32:40.073 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:33:26.531 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:33:26,882 - INFO - AFOLU model run successfully completed
2026-09-17 17:33:26,883 - INFO - Running CircularEconomy model
2026-09-17 17:33:26,903 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:33:26,903 - INFO - Running IPPU model
2026-09-17 17:33:26,936 - INFO - IPPU model run successfully completed
2026-09-17 17:33:26,936 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:33:26,945 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:33:26,983 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:33:26,984 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:33:27.494 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:33:27.538 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:34:26,219 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:34:26,225 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:34:26,225 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:34:26,256 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:34:26,256 - INFO - Appending Socioeconomic outputs
2026-09-17 17:34:26,260 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:34:26,262 - INFO - Model run for primary_id = 119119 successfully completed in 59.59 seconds (n_tries = 1).
2026-09-17 17:34:26,264 - INFO - Trying run primary_id = 120120 in region morocco
2026-09-17 17:34:26,265 - INFO - Running AFOLU model

2026-17-Sep 17:33:33.664 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:33:33.711 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:34:26.144 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:34:26,482 - INFO - AFOLU model run successfully completed
2026-09-17 17:34:26,482 - INFO - Running CircularEconomy model
2026-09-17 17:34:26,505 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:34:26,505 - INFO - Running IPPU model
2026-09-17 17:34:26,538 - INFO - IPPU model run successfully completed
2026-09-17 17:34:26,538 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:34:26,547 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:34:26,586 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:34:26,586 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:34:27.108 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:34:27.151 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:34:56,408 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:34:56,414 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:34:56,414 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:34:56,444 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:34:56,445 - INFO - Appending Socioeconomic outputs
2026-09-17 17:34:56,449 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:34:56,450 - INFO - Model run for primary_id = 120120 successfully completed in 30.19 seconds (n_tries = 1).
2026-09-17 17:34:56,453 - INFO - Trying run primary_id = 121121 in region morocco
2026-09-17 17:34:56,453 - INFO - Running AFOLU model

2026-17-Sep 17:34:33.115 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:34:33.165 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:34:56.323 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:34:56,670 - INFO - AFOLU model run successfully completed
2026-09-17 17:34:56,671 - INFO - Running CircularEconomy model
2026-09-17 17:34:56,691 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:34:56,691 - INFO - Running IPPU model
2026-09-17 17:34:56,723 - INFO - IPPU model run successfully completed
2026-09-17 17:34:56,724 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:34:56,732 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:34:56,773 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:34:56,774 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:34:57.487 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:34:57.531 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:35:37,594 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:35:37,600 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:35:37,600 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:35:37,633 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:35:37,633 - INFO - Appending Socioeconomic outputs
2026-09-17 17:35:37,638 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:35:37,639 - INFO - Model run for primary_id = 121121 successfully completed in 41.19 seconds (n_tries = 1).
2026-09-17 17:35:37,642 - INFO - Trying run primary_id = 122122 in region morocco
2026-09-17 17:35:37,642 - INFO - Running AFOLU model

2026-17-Sep 17:35:04.020 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:35:04.073 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:35:37.520 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:35:37,863 - INFO - AFOLU model run successfully completed
2026-09-17 17:35:37,864 - INFO - Running CircularEconomy model
2026-09-17 17:35:37,884 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:35:37,884 - INFO - Running IPPU model
2026-09-17 17:35:37,917 - INFO - IPPU model run successfully completed
2026-09-17 17:35:37,917 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:35:37,926 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:35:37,965 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:35:37,965 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:35:38.508 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:35:38.553 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:36:14,107 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:36:14,113 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:36:14,113 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:36:14,143 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:36:14,143 - INFO - Appending Socioeconomic outputs
2026-09-17 17:36:14,147 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:36:14,149 - INFO - Model run for primary_id = 122122 successfully completed in 36.51 seconds (n_tries = 1).
2026-09-17 17:36:14,151 - INFO - Trying run primary_id = 123123 in region morocco
2026-09-17 17:36:14,151 - INFO - Running AFOLU model

2026-17-Sep 17:35:44.680 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:35:44.734 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:36:14.034 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:36:14,360 - INFO - AFOLU model run successfully completed
2026-09-17 17:36:14,360 - INFO - Running CircularEconomy model
2026-09-17 17:36:14,384 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:36:14,384 - INFO - Running IPPU model
2026-09-17 17:36:14,422 - INFO - IPPU model run successfully completed
2026-09-17 17:36:14,422 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:36:14,431 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:36:14,469 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:36:14,469 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:36:14.988 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:36:15.031 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:36:59,223 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:36:59,229 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:36:59,229 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:36:59,261 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:36:59,261 - INFO - Appending Socioeconomic outputs
2026-09-17 17:36:59,265 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:36:59,267 - INFO - Model run for primary_id = 123123 successfully completed in 45.12 seconds (n_tries = 1).

2026-17-Sep 17:36:21.246 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:36:21.301 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:36:59.134 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:36:59,499 - INFO - Table MODEL_OUTPUT successfully written to /Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-09-17T17;28;54.353650/sisepuede_run_2026-09-17T17;28;54.353650_output_database/MODEL_OUTPUT.csv.
2026-09-17 17:36:59,745 - INFO - Table MODEL_INPUT successfully written to /Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-09-17T17;28;54.353650/sisepuede_run_2026-09-17T17;28;54.353650_output_database/MODEL_INPUT.csv.
2026-09-17 17:36:59,747 - INFO - Trying run primary_id = 124124 in region morocco
2026-09-17 17:36:59,748 - INFO - Running AFOLU model
2026-09-17 17:36:59,956 - INFO - AFOLU model run successfully completed
2026-09-17 17:36:59,957 - INFO - Running CircularEconomy model
2026-09-17 17:36:59,977 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:36:59,977 - INFO - Running IPPU model
2026-09-17 17:37:00,009 - INFO - IPPU model run successfully completed
2026-09-17 17:37:00,009 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:37:00,018 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:37:00,057 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:37:00,057 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:37:00.790 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:37:00.834 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:37:47,699 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:37:47,706 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:37:47,706 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:37:47,737 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:37:47,737 - INFO - Appending Socioeconomic outputs
2026-09-17 17:37:47,741 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:37:47,743 - INFO - Model run for primary_id = 124124 successfully completed in 47.99 seconds (n_tries = 1).
2026-09-17 17:37:47,747 - INFO - Trying run primary_id = 125125 in region morocco
2026-09-17 17:37:47,747 - INFO - Running AFOLU model

2026-17-Sep 17:37:07.277 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:37:07.331 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:37:47.620 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:37:47,953 - INFO - AFOLU model run successfully completed
2026-09-17 17:37:47,953 - INFO - Running CircularEconomy model
2026-09-17 17:37:47,972 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:37:47,973 - INFO - Running IPPU model
2026-09-17 17:37:48,004 - INFO - IPPU model run successfully completed
2026-09-17 17:37:48,004 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:37:48,012 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:37:48,050 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:37:48,050 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:37:48.565 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:37:48.610 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:38:27,666 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:38:27,672 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:38:27,672 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:38:27,701 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:38:27,701 - INFO - Appending Socioeconomic outputs
2026-09-17 17:38:27,705 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:38:27,706 - INFO - Model run for primary_id = 125125 successfully completed in 39.96 seconds (n_tries = 1).
2026-09-17 17:38:27,708 - INFO - Trying run primary_id = 126126 in region morocco
2026-09-17 17:38:27,709 - INFO - Running AFOLU model

2026-17-Sep 17:37:54.966 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:37:55.021 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:38:27.597 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:38:27,911 - INFO - AFOLU model run successfully completed
2026-09-17 17:38:27,911 - INFO - Running CircularEconomy model
2026-09-17 17:38:27,930 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:38:27,930 - INFO - Running IPPU model
2026-09-17 17:38:27,960 - INFO - IPPU model run successfully completed
2026-09-17 17:38:27,961 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:38:27,969 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:38:28,005 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:38:28,005 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:38:28.500 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:38:28.541 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:39:43,748 - INFO - NemoMod ran successfully with the following status: OTHER_ERROR
2026-09-17 17:39:43,754 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:39:43,754 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:39:43,791 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:39:43,792 - INFO - Appending Socioeconomic outputs
2026-09-17 17:39:43,796 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:39:43,797 - INFO - Model run for primary_id = 126126 successfully completed in 76.09 seconds (n_tries = 1).
2026-09-17 17:39:43,799 - INFO - Trying run primary_id = 127127 in region morocco
2026-09-17 17:39:43,800 - INFO - Running AFOLU model

2026-17-Sep 17:38:34.714 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:38:34.768 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:39:43.681 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:39:44,003 - INFO - AFOLU model run successfully completed
2026-09-17 17:39:44,003 - INFO - Running CircularEconomy model
2026-09-17 17:39:44,023 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:39:44,023 - INFO - Running IPPU model
2026-09-17 17:39:44,053 - INFO - IPPU model run successfully completed
2026-09-17 17:39:44,053 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:39:44,062 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:39:44,098 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:39:44,098 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:39:44.834 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:39:44.876 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:40:23,750 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:40:23,756 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:40:23,756 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:40:23,784 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:40:23,784 - INFO - Appending Socioeconomic outputs
2026-09-17 17:40:23,788 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:40:23,790 - INFO - Model run for primary_id = 127127 successfully completed in 39.99 seconds (n_tries = 1).
2026-09-17 17:40:23,792 - INFO - Trying run primary_id = 128128 in region morocco
2026-09-17 17:40:23,792 - INFO - Running AFOLU model

2026-17-Sep 17:39:51.154 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:39:51.207 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:40:23.681 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:40:23,993 - INFO - AFOLU model run successfully completed
2026-09-17 17:40:23,993 - INFO - Running CircularEconomy model
2026-09-17 17:40:24,012 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:40:24,012 - INFO - Running IPPU model
2026-09-17 17:40:24,042 - INFO - IPPU model run successfully completed
2026-09-17 17:40:24,042 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:40:24,050 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:40:24,087 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:40:24,087 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:40:24.579 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:40:24.621 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:41:05,573 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:41:05,581 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:41:05,582 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:41:05,612 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:41:05,612 - INFO - Appending Socioeconomic outputs
2026-09-17 17:41:05,617 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:41:05,618 - INFO - Model run for primary_id = 128128 successfully completed in 41.83 seconds (n_tries = 1).
2026-09-17 17:41:05,621 - INFO - Trying run primary_id = 129129 in region morocco
2026-09-17 17:41:05,622 - INFO - Running AFOLU model

2026-17-Sep 17:40:30.877 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:40:30.932 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:41:05.493 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:41:05,841 - INFO - AFOLU model run successfully completed
2026-09-17 17:41:05,841 - INFO - Running CircularEconomy model
2026-09-17 17:41:05,861 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:41:05,862 - INFO - Running IPPU model
2026-09-17 17:41:05,894 - INFO - IPPU model run successfully completed
2026-09-17 17:41:05,894 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:41:05,903 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:41:05,941 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:41:05,941 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:41:06.471 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:41:06.517 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:41:46,465 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:41:46,471 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:41:46,471 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:41:46,502 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:41:46,502 - INFO - Appending Socioeconomic outputs
2026-09-17 17:41:46,506 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:41:46,508 - INFO - Model run for primary_id = 129129 successfully completed in 40.89 seconds (n_tries = 1).
2026-09-17 17:41:46,511 - INFO - Trying run primary_id = 130130 in region morocco
2026-09-17 17:41:46,511 - INFO - Running AFOLU model

2026-17-Sep 17:41:12.883 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:41:12.937 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:41:46.391 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:41:46,718 - INFO - AFOLU model run successfully completed
2026-09-17 17:41:46,718 - INFO - Running CircularEconomy model
2026-09-17 17:41:46,743 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:41:46,743 - INFO - Running IPPU model
2026-09-17 17:41:46,782 - INFO - IPPU model run successfully completed
2026-09-17 17:41:46,783 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:41:46,792 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:41:46,830 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:41:46,830 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:41:47.365 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:41:47.411 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:42:27,430 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:42:27,437 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:42:27,437 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:42:27,467 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:42:27,467 - INFO - Appending Socioeconomic outputs
2026-09-17 17:42:27,471 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:42:27,473 - INFO - Model run for primary_id = 130130 successfully completed in 40.96 seconds (n_tries = 1).
2026-09-17 17:42:27,476 - INFO - Trying run primary_id = 131131 in region morocco
2026-09-17 17:42:27,476 - INFO - Running AFOLU model

2026-17-Sep 17:41:54.024 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:41:54.081 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:42:27.355 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:42:27,685 - INFO - AFOLU model run successfully completed
2026-09-17 17:42:27,685 - INFO - Running CircularEconomy model
2026-09-17 17:42:27,705 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:42:27,705 - INFO - Running IPPU model
2026-09-17 17:42:27,737 - INFO - IPPU model run successfully completed
2026-09-17 17:42:27,737 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:42:27,745 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:42:27,784 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:42:27,784 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:42:28.532 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:42:28.578 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:43:08,592 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:43:08,598 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:43:08,598 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:43:08,629 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:43:08,629 - INFO - Appending Socioeconomic outputs
2026-09-17 17:43:08,633 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:43:08,635 - INFO - Model run for primary_id = 131131 successfully completed in 41.16 seconds (n_tries = 1).
2026-09-17 17:43:08,639 - INFO - Trying run primary_id = 132132 in region morocco
2026-09-17 17:43:08,639 - INFO - Running AFOLU model

2026-17-Sep 17:42:35.230 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:42:35.286 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:43:08.494 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:43:08,862 - INFO - AFOLU model run successfully completed
2026-09-17 17:43:08,863 - INFO - Running CircularEconomy model
2026-09-17 17:43:08,883 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:43:08,883 - INFO - Running IPPU model
2026-09-17 17:43:08,914 - INFO - IPPU model run successfully completed
2026-09-17 17:43:08,914 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:43:08,922 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:43:08,960 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:43:08,960 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:43:09.485 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:43:09.528 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:43:50,288 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:43:50,294 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:43:50,295 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:43:50,324 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:43:50,324 - INFO - Appending Socioeconomic outputs
2026-09-17 17:43:50,328 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:43:50,330 - INFO - Model run for primary_id = 132132 successfully completed in 41.69 seconds (n_tries = 1).
2026-09-17 17:43:50,333 - INFO - Trying run primary_id = 133133 in region morocco
2026-09-17 17:43:50,333 - INFO - Running AFOLU model

2026-17-Sep 17:43:16.006 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:43:16.061 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:43:50.216 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:43:50,540 - INFO - AFOLU model run successfully completed
2026-09-17 17:43:50,540 - INFO - Running CircularEconomy model
2026-09-17 17:43:50,560 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:43:50,560 - INFO - Running IPPU model
2026-09-17 17:43:50,592 - INFO - IPPU model run successfully completed
2026-09-17 17:43:50,592 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:43:50,600 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:43:50,637 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:43:50,638 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:43:51.149 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:43:51.195 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:44:31,104 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:44:31,109 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:44:31,109 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:44:31,139 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:44:31,139 - INFO - Appending Socioeconomic outputs
2026-09-17 17:44:31,143 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:44:31,145 - INFO - Model run for primary_id = 133133 successfully completed in 40.81 seconds (n_tries = 1).

2026-17-Sep 17:43:57.663 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:43:57.723 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:44:31.035 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:44:31,597 - INFO - Table MODEL_OUTPUT successfully appended to /Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-09-17T17;28;54.353650/sisepuede_run_2026-09-17T17;28;54.353650_output_database/MODEL_OUTPUT.csv.
2026-09-17 17:44:31,877 - INFO - Table MODEL_INPUT successfully appended to /Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-09-17T17;28;54.353650/sisepuede_run_2026-09-17T17;28;54.353650_output_database/MODEL_INPUT.csv.
2026-09-17 17:44:31,879 - INFO - Trying run primary_id = 134134 in region morocco
2026-09-17 17:44:31,879 - INFO - Running AFOLU model
2026-09-17 17:44:32,076 - INFO - AFOLU model run successfully completed
2026-09-17 17:44:32,077 - INFO - Running CircularEconomy model
2026-09-17 17:44:32,096 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:44:32,096 - INFO - Running IPPU model
2026-09-17 17:44:32,127 - INFO - IPPU model run successfully completed
2026-09-17 17:44:32,128 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:44:32,137 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:44:32,185 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:44:32,185 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:44:32.711 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:44:32.752 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:45:10,679 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:45:10,687 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:45:10,687 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:45:10,718 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:45:10,718 - INFO - Appending Socioeconomic outputs
2026-09-17 17:45:10,722 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:45:10,724 - INFO - Model run for primary_id = 134134 successfully completed in 38.84 seconds (n_tries = 1).
2026-09-17 17:45:10,727 - INFO - Trying run primary_id = 135135 in region morocco
2026-09-17 17:45:10,728 - INFO - Running AFOLU model

2026-17-Sep 17:44:39.124 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:44:39.178 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:45:10.596 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:45:10,941 - INFO - AFOLU model run successfully completed
2026-09-17 17:45:10,941 - INFO - Running CircularEconomy model
2026-09-17 17:45:10,962 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:45:10,962 - INFO - Running IPPU model
2026-09-17 17:45:10,995 - INFO - IPPU model run successfully completed
2026-09-17 17:45:10,995 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:45:11,004 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:45:11,044 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:45:11,044 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:45:11.572 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:45:11.617 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:45:18.145 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:45:18.200 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].

2026-09-17 17:45:52,856 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:45:52,862 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:45:52,862 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:45:52,896 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:45:52,896 - INFO - Appending Socioeconomic outputs
2026-09-17 17:45:52,901 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:45:52,902 - INFO - Model run for primary_id = 135135 successfully completed in 42.17 seconds (n_tries = 1).
2026-09-17 17:45:52,906 - INFO - Trying run primary_id = 136136 in region morocco
2026-09-17 17:45:52,906 - INFO - Running AFOLU model

2026-17-Sep 17:45:52.776 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:45:53,121 - INFO - AFOLU model run successfully completed
2026-09-17 17:45:53,122 - INFO - Running CircularEconomy model
2026-09-17 17:45:53,142 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:45:53,143 - INFO - Running IPPU model
2026-09-17 17:45:53,175 - INFO - IPPU model run successfully completed
2026-09-17 17:45:53,175 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:45:53,183 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:45:53,220 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:45:53,220 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:45:53.952 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:45:53.996 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:46:32,541 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:46:32,548 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:46:32,548 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:46:32,578 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:46:32,579 - INFO - Appending Socioeconomic outputs
2026-09-17 17:46:32,583 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:46:32,584 - INFO - Model run for primary_id = 136136 successfully completed in 39.68 seconds (n_tries = 1).
2026-09-17 17:46:32,589 - INFO - Trying run primary_id = 137137 in region morocco
2026-09-17 17:46:32,589 - INFO - Running AFOLU model

2026-17-Sep 17:46:00.118 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:46:00.172 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:46:32.466 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:46:32,795 - INFO - AFOLU model run successfully completed
2026-09-17 17:46:32,795 - INFO - Running CircularEconomy model
2026-09-17 17:46:32,819 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:46:32,819 - INFO - Running IPPU model
2026-09-17 17:46:32,858 - INFO - IPPU model run successfully completed
2026-09-17 17:46:32,858 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:46:32,867 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:46:32,905 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:46:32,906 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:46:33.420 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:46:33.463 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:47:13,630 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:47:13,636 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:47:13,636 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:47:13,667 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:47:13,667 - INFO - Appending Socioeconomic outputs
2026-09-17 17:47:13,671 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:47:13,673 - INFO - Model run for primary_id = 137137 successfully completed in 41.08 seconds (n_tries = 1).
2026-09-17 17:47:13,676 - INFO - Trying run primary_id = 138138 in region morocco
2026-09-17 17:47:13,677 - INFO - Running AFOLU model

2026-17-Sep 17:46:40.066 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:46:40.122 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:47:13.557 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:47:13,918 - INFO - AFOLU model run successfully completed
2026-09-17 17:47:13,918 - INFO - Running CircularEconomy model
2026-09-17 17:47:13,940 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:47:13,940 - INFO - Running IPPU model
2026-09-17 17:47:13,973 - INFO - IPPU model run successfully completed
2026-09-17 17:47:13,974 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:47:13,983 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:47:14,023 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:47:14,023 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:47:14.563 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:47:14.606 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:48:02,950 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:48:02,956 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:48:02,956 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:48:02,986 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:48:02,986 - INFO - Appending Socioeconomic outputs
2026-09-17 17:48:02,990 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:48:02,992 - INFO - Model run for primary_id = 138138 successfully completed in 49.32 seconds (n_tries = 1).
2026-09-17 17:48:02,995 - INFO - Trying run primary_id = 139139 in region morocco
2026-09-17 17:48:02,996 - INFO - Running AFOLU model

2026-17-Sep 17:47:21.357 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:47:21.410 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:48:02.878 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:48:03,209 - INFO - AFOLU model run successfully completed
2026-09-17 17:48:03,210 - INFO - Running CircularEconomy model
2026-09-17 17:48:03,235 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:48:03,235 - INFO - Running IPPU model
2026-09-17 17:48:03,274 - INFO - IPPU model run successfully completed
2026-09-17 17:48:03,274 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:48:03,283 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:48:03,322 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:48:03,323 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:48:04.059 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:48:04.102 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:48:44,232 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:48:44,238 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:48:44,238 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:48:44,267 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:48:44,268 - INFO - Appending Socioeconomic outputs
2026-09-17 17:48:44,272 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:48:44,274 - INFO - Model run for primary_id = 139139 successfully completed in 41.28 seconds (n_tries = 1).
2026-09-17 17:48:44,277 - INFO - Trying run primary_id = 140140 in region morocco
2026-09-17 17:48:44,278 - INFO - Running AFOLU model

2026-17-Sep 17:48:10.622 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:48:10.683 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:48:44.145 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:48:44,482 - INFO - AFOLU model run successfully completed
2026-09-17 17:48:44,483 - INFO - Running CircularEconomy model
2026-09-17 17:48:44,503 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:48:44,503 - INFO - Running IPPU model
2026-09-17 17:48:44,534 - INFO - IPPU model run successfully completed
2026-09-17 17:48:44,534 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:48:44,543 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:48:44,586 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:48:44,586 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:48:45.125 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:48:45.170 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:49:19,552 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:49:19,560 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:49:19,560 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:49:19,591 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:49:19,592 - INFO - Appending Socioeconomic outputs
2026-09-17 17:49:19,596 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:49:19,597 - INFO - Model run for primary_id = 140140 successfully completed in 35.32 seconds (n_tries = 1).
2026-09-17 17:49:19,601 - INFO - Trying run primary_id = 141141 in region morocco
2026-09-17 17:49:19,601 - INFO - Running AFOLU model

2026-17-Sep 17:48:51.773 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:48:51.828 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:49:19.474 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:49:19,812 - INFO - AFOLU model run successfully completed
2026-09-17 17:49:19,812 - INFO - Running CircularEconomy model
2026-09-17 17:49:19,835 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:49:19,835 - INFO - Running IPPU model
2026-09-17 17:49:19,869 - INFO - IPPU model run successfully completed
2026-09-17 17:49:19,869 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:49:19,878 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:49:19,930 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:49:19,931 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:49:20.508 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:49:20.555 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:50:10,046 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:50:10,055 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:50:10,055 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:50:10,088 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:50:10,088 - INFO - Appending Socioeconomic outputs
2026-09-17 17:50:10,093 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:50:10,095 - INFO - Model run for primary_id = 141141 successfully completed in 50.49 seconds (n_tries = 1).
2026-09-17 17:50:10,101 - INFO - Trying run primary_id = 142142 in region morocco
2026-09-17 17:50:10,101 - INFO - Running AFOLU model

2026-17-Sep 17:49:27.101 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:49:27.155 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:50:09.959 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:50:10,319 - INFO - AFOLU model run successfully completed
2026-09-17 17:50:10,319 - INFO - Running CircularEconomy model
2026-09-17 17:50:10,339 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:50:10,339 - INFO - Running IPPU model
2026-09-17 17:50:10,371 - INFO - IPPU model run successfully completed
2026-09-17 17:50:10,371 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:50:10,380 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:50:10,418 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:50:10,418 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:50:10.947 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:50:10.993 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:50:50,781 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:50:50,789 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:50:50,790 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:50:50,820 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:50:50,820 - INFO - Appending Socioeconomic outputs
2026-09-17 17:50:50,824 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:50:50,826 - INFO - Model run for primary_id = 142142 successfully completed in 40.72 seconds (n_tries = 1).
2026-09-17 17:50:50,832 - INFO - Trying run primary_id = 143143 in region morocco
2026-09-17 17:50:50,833 - INFO - Running AFOLU model

2026-17-Sep 17:50:17.631 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:50:17.685 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:50:50.706 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:50:51,039 - INFO - AFOLU model run successfully completed
2026-09-17 17:50:51,039 - INFO - Running CircularEconomy model
2026-09-17 17:50:51,059 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:50:51,059 - INFO - Running IPPU model
2026-09-17 17:50:51,091 - INFO - IPPU model run successfully completed
2026-09-17 17:50:51,091 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:50:51,100 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:50:51,137 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:50:51,138 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:50:51.936 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:50:51.979 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:51:25,324 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:51:25,331 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:51:25,331 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:51:25,361 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:51:25,361 - INFO - Appending Socioeconomic outputs
2026-09-17 17:51:25,365 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:51:25,367 - INFO - Model run for primary_id = 143143 successfully completed in 34.53 seconds (n_tries = 1).

2026-17-Sep 17:50:58.626 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:50:58.685 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:51:25.251 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:51:25,618 - INFO - Table MODEL_OUTPUT successfully appended to /Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-09-17T17;28;54.353650/sisepuede_run_2026-09-17T17;28;54.353650_output_database/MODEL_OUTPUT.csv.
2026-09-17 17:51:25,900 - INFO - Table MODEL_INPUT successfully appended to /Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-09-17T17;28;54.353650/sisepuede_run_2026-09-17T17;28;54.353650_output_database/MODEL_INPUT.csv.
2026-09-17 17:51:25,904 - INFO - Trying run primary_id = 144144 in region morocco
2026-09-17 17:51:25,905 - INFO - Running AFOLU model
2026-09-17 17:51:26,110 - INFO - AFOLU model run successfully completed
2026-09-17 17:51:26,110 - INFO - Running CircularEconomy model
2026-09-17 17:51:26,130 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:51:26,130 - INFO - Running IPPU model
2026-09-17 17:51:26,161 - INFO - IPPU model run successfully completed
2026-09-17 17:51:26,161 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:51:26,169 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:51:26,206 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:51:26,207 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:51:26.719 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:51:26.765 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:52:06,805 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:52:06,812 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:52:06,812 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:52:06,845 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:52:06,845 - INFO - Appending Socioeconomic outputs
2026-09-17 17:52:06,850 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:52:06,852 - INFO - Model run for primary_id = 144144 successfully completed in 40.95 seconds (n_tries = 1).
2026-09-17 17:52:06,858 - INFO - Trying run primary_id = 145145 in region morocco
2026-09-17 17:52:06,858 - INFO - Running AFOLU model

2026-17-Sep 17:51:33.162 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:51:33.218 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:52:06.723 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:52:07,069 - INFO - AFOLU model run successfully completed
2026-09-17 17:52:07,069 - INFO - Running CircularEconomy model
2026-09-17 17:52:07,090 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:52:07,090 - INFO - Running IPPU model
2026-09-17 17:52:07,122 - INFO - IPPU model run successfully completed
2026-09-17 17:52:07,122 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:52:07,132 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:52:07,183 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:52:07,183 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:52:07.926 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:52:07.972 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:52:49,443 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:52:49,451 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:52:49,451 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:52:49,482 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:52:49,483 - INFO - Appending Socioeconomic outputs
2026-09-17 17:52:49,487 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:52:49,489 - INFO - Model run for primary_id = 145145 successfully completed in 42.63 seconds (n_tries = 1).
2026-09-17 17:52:49,497 - INFO - Trying run primary_id = 146146 in region morocco
2026-09-17 17:52:49,497 - INFO - Running AFOLU model

2026-17-Sep 17:52:14.598 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:52:14.652 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:52:49.368 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:52:49,708 - INFO - AFOLU model run successfully completed
2026-09-17 17:52:49,709 - INFO - Running CircularEconomy model
2026-09-17 17:52:49,730 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:52:49,730 - INFO - Running IPPU model
2026-09-17 17:52:49,762 - INFO - IPPU model run successfully completed
2026-09-17 17:52:49,763 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:52:49,772 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:52:49,812 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:52:49,812 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:52:50.351 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:52:50.396 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:53:28,476 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:53:28,482 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:53:28,482 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:53:28,515 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:53:28,515 - INFO - Appending Socioeconomic outputs
2026-09-17 17:53:28,520 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:53:28,522 - INFO - Model run for primary_id = 146146 successfully completed in 39.02 seconds (n_tries = 1).
2026-09-17 17:53:28,530 - INFO - Trying run primary_id = 147147 in region morocco
2026-09-17 17:53:28,530 - INFO - Running AFOLU model

2026-17-Sep 17:52:57.073 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:52:57.126 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:53:28.389 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:53:28,755 - INFO - AFOLU model run successfully completed
2026-09-17 17:53:28,755 - INFO - Running CircularEconomy model
2026-09-17 17:53:28,778 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:53:28,779 - INFO - Running IPPU model
2026-09-17 17:53:28,813 - INFO - IPPU model run successfully completed
2026-09-17 17:53:28,813 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:53:28,822 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:53:28,865 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:53:28,866 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:53:29.414 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:53:29.459 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:56:02,104 - INFO - NemoMod ran successfully with the following status: OTHER_ERROR
2026-09-17 17:56:02,116 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:56:02,116 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:56:02,148 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:56:02,148 - INFO - Appending Socioeconomic outputs
2026-09-17 17:56:02,152 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:56:02,154 - INFO - Model run for primary_id = 147147 successfully completed in 153.62 seconds (n_tries = 1).
2026-09-17 17:56:02,160 - INFO - Trying run primary_id = 148148 in region morocco
2026-09-17 17:56:02,161 - INFO - Running AFOLU model

2026-17-Sep 17:53:36.353 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:53:36.408 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:56:02.022 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:56:02,380 - INFO - AFOLU model run successfully completed
2026-09-17 17:56:02,380 - INFO - Running CircularEconomy model
2026-09-17 17:56:02,401 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:56:02,401 - INFO - Running IPPU model
2026-09-17 17:56:02,433 - INFO - IPPU model run successfully completed
2026-09-17 17:56:02,434 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:56:02,442 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:56:02,480 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:56:02,480 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:56:03.293 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:56:03.339 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:56:37,481 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:56:37,491 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:56:37,491 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:56:37,522 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:56:37,523 - INFO - Appending Socioeconomic outputs
2026-09-17 17:56:37,527 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:56:37,529 - INFO - Model run for primary_id = 148148 successfully completed in 35.37 seconds (n_tries = 1).
2026-09-17 17:56:37,537 - INFO - Trying run primary_id = 149149 in region morocco
2026-09-17 17:56:37,537 - INFO - Running AFOLU model

2026-17-Sep 17:56:10.041 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:56:10.097 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:56:37.398 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:56:37,747 - INFO - AFOLU model run successfully completed
2026-09-17 17:56:37,748 - INFO - Running CircularEconomy model
2026-09-17 17:56:37,772 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:56:37,773 - INFO - Running IPPU model
2026-09-17 17:56:37,812 - INFO - IPPU model run successfully completed
2026-09-17 17:56:37,812 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:56:37,821 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:56:37,859 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:56:37,860 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:56:38.380 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:56:38.428 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:57:24,250 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:57:24,256 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:57:24,256 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:57:24,286 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:57:24,286 - INFO - Appending Socioeconomic outputs
2026-09-17 17:57:24,291 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:57:24,292 - INFO - Model run for primary_id = 149149 successfully completed in 46.76 seconds (n_tries = 1).
2026-09-17 17:57:24,301 - INFO - Trying run primary_id = 150150 in region morocco
2026-09-17 17:57:24,301 - INFO - Running AFOLU model

2026-17-Sep 17:56:45.007 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:56:45.061 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:57:24.176 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:57:24,517 - INFO - AFOLU model run successfully completed
2026-09-17 17:57:24,517 - INFO - Running CircularEconomy model
2026-09-17 17:57:24,537 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:57:24,537 - INFO - Running IPPU model
2026-09-17 17:57:24,568 - INFO - IPPU model run successfully completed
2026-09-17 17:57:24,568 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:57:24,576 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:57:24,613 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:57:24,613 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:57:25.138 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:57:25.187 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:58:04,549 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:58:04,555 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:58:04,555 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:58:04,585 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:58:04,585 - INFO - Appending Socioeconomic outputs
2026-09-17 17:58:04,589 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:58:04,591 - INFO - Model run for primary_id = 150150 successfully completed in 40.29 seconds (n_tries = 1).
2026-09-17 17:58:04,597 - INFO - Trying run primary_id = 151151 in region morocco
2026-09-17 17:58:04,597 - INFO - Running AFOLU model

2026-17-Sep 17:57:31.672 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:57:31.727 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:58:04.474 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:58:04,812 - INFO - AFOLU model run successfully completed
2026-09-17 17:58:04,813 - INFO - Running CircularEconomy model
2026-09-17 17:58:04,836 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:58:04,836 - INFO - Running IPPU model
2026-09-17 17:58:04,869 - INFO - IPPU model run successfully completed
2026-09-17 17:58:04,869 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:58:04,878 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:58:04,919 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:58:04,919 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:58:05.465 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:58:05.509 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 17:58:41,557 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:58:41,563 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:58:41,563 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:58:41,592 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:58:41,593 - INFO - Appending Socioeconomic outputs
2026-09-17 17:58:41,597 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:58:41,598 - INFO - Model run for primary_id = 151151 successfully completed in 37.0 seconds (n_tries = 1).
2026-09-17 17:58:41,602 - INFO - Trying run primary_id = 152152 in region morocco
2026-09-17 17:58:41,602 - INFO - Running AFOLU model

2026-17-Sep 17:58:12.054 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:58:12.108 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 17:58:41.483 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:58:41,809 - INFO - AFOLU model run successfully completed
2026-09-17 17:58:41,810 - INFO - Running CircularEconomy model
2026-09-17 17:58:41,833 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:58:41,834 - INFO - Running IPPU model
2026-09-17 17:58:41,874 - INFO - IPPU model run successfully completed
2026-09-17 17:58:41,874 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:58:41,883 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:58:41,920 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:58:41,921 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:58:42.625 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:58:42.668 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:58:49.109 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:58:49.164 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].

2026-09-17 17:59:19,427 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 17:59:19,433 - INFO - EnergyProduction model run successfully completed
2026-09-17 17:59:19,433 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 17:59:19,463 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 17:59:19,463 - INFO - Appending Socioeconomic outputs
2026-09-17 17:59:19,467 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 17:59:19,469 - INFO - Model run for primary_id = 152152 successfully completed in 37.87 seconds (n_tries = 1).
2026-09-17 17:59:19,471 - INFO - Trying run primary_id = 153153 in region morocco
2026-09-17 17:59:19,471 - INFO - Running AFOLU model

2026-17-Sep 17:59:19.356 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 17:59:19,681 - INFO - AFOLU model run successfully completed
2026-09-17 17:59:19,682 - INFO - Running CircularEconomy model
2026-09-17 17:59:19,702 - INFO - CircularEconomy model run successfully completed
2026-09-17 17:59:19,702 - INFO - Running IPPU model
2026-09-17 17:59:19,743 - INFO - IPPU model run successfully completed
2026-09-17 17:59:19,743 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 17:59:19,752 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 17:59:19,789 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 17:59:19,790 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 17:59:20.319 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 17:59:20.362 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 18:00:41,960 - INFO - NemoMod ran successfully with the following status: OTHER_ERROR
2026-09-17 18:00:41,970 - INFO - EnergyProduction model run successfully completed
2026-09-17 18:00:41,970 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 18:00:42,002 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 18:00:42,002 - INFO - Appending Socioeconomic outputs
2026-09-17 18:00:42,007 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 18:00:42,008 - INFO - Model run for primary_id = 153153 successfully completed in 82.54 seconds (n_tries = 1).

2026-17-Sep 17:59:26.899 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 17:59:26.954 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 18:00:41.880 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 18:00:42,264 - INFO - Table MODEL_OUTPUT successfully appended to /Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-09-17T17;28;54.353650/sisepuede_run_2026-09-17T17;28;54.353650_output_database/MODEL_OUTPUT.csv.
2026-09-17 18:00:42,565 - INFO - Table MODEL_INPUT successfully appended to /Users/fabianfuentes/miniconda3/envs/ssp_morocco_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-09-17T17;28;54.353650/sisepuede_run_2026-09-17T17;28;54.353650_output_database/MODEL_INPUT.csv.
2026-09-17 18:00:42,567 - INFO - Trying run primary_id = 154154 in region morocco
2026-09-17 18:00:42,567 - INFO - Running AFOLU model
2026-09-17 18:00:42,779 - INFO - AFOLU model run successfully completed
2026-09-17 18:00:42,779 - INFO - Running CircularEconomy model
2026-09-17 18:00:42,799 - INFO - CircularEconomy model run successfully completed
2026-09-17 18:00:42,799 - INFO - Running IPPU model
2026-09-17 18:00:42,831 - INFO - IPPU model run successfully completed
2026-09-17 18:00:42,831 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 18:00:42,840 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 18:00:42,878 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 18:00:42,878 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 18:00:43.641 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 18:00:43.685 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 18:01:20,494 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 18:01:20,499 - INFO - EnergyProduction model run successfully completed
2026-09-17 18:01:20,500 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 18:01:20,534 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 18:01:20,534 - INFO - Appending Socioeconomic outputs
2026-09-17 18:01:20,539 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 18:01:20,541 - INFO - Model run for primary_id = 154154 successfully completed in 37.97 seconds (n_tries = 1).
2026-09-17 18:01:20,543 - INFO - Trying run primary_id = 155155 in region morocco
2026-09-17 18:01:20,544 - INFO - Running AFOLU model

2026-17-Sep 18:00:50.749 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 18:00:50.802 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 18:01:20.402 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 18:01:20,774 - INFO - AFOLU model run successfully completed
2026-09-17 18:01:20,775 - INFO - Running CircularEconomy model
2026-09-17 18:01:20,798 - INFO - CircularEconomy model run successfully completed
2026-09-17 18:01:20,798 - INFO - Running IPPU model
2026-09-17 18:01:20,835 - INFO - IPPU model run successfully completed
2026-09-17 18:01:20,835 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 18:01:20,844 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 18:01:20,886 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 18:01:20,886 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 18:01:21.492 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 18:01:21.540 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 18:02:01,129 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 18:02:01,135 - INFO - EnergyProduction model run successfully completed
2026-09-17 18:02:01,135 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 18:02:01,167 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 18:02:01,168 - INFO - Appending Socioeconomic outputs
2026-09-17 18:02:01,172 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 18:02:01,173 - INFO - Model run for primary_id = 155155 successfully completed in 40.63 seconds (n_tries = 1).
2026-09-17 18:02:01,176 - INFO - Trying run primary_id = 156156 in region morocco
2026-09-17 18:02:01,176 - INFO - Running AFOLU model

2026-17-Sep 18:01:27.877 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 18:01:27.931 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 18:02:01.055 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 18:02:01,386 - INFO - AFOLU model run successfully completed
2026-09-17 18:02:01,387 - INFO - Running CircularEconomy model
2026-09-17 18:02:01,406 - INFO - CircularEconomy model run successfully completed
2026-09-17 18:02:01,407 - INFO - Running IPPU model
2026-09-17 18:02:01,439 - INFO - IPPU model run successfully completed
2026-09-17 18:02:01,439 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 18:02:01,448 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 18:02:01,486 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 18:02:01,487 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-17-Sep 18:02:02.011 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-17-Sep 18:02:02.058 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].

2026-09-17 18:02:51,095 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-09-17 18:02:51,101 - INFO - EnergyProduction model run successfully completed
2026-09-17 18:02:51,102 - INFO - Running Energy (Fugitive Emissions) and adjusting conversion emissions for biomass.
2026-09-17 18:02:51,143 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-09-17 18:02:51,143 - INFO - Appending Socioeconomic outputs
2026-09-17 18:02:51,147 - INFO - Socioeconomic outputs successfully appended.
2026-09-17 18:02:51,149 - INFO - Model run for primary_id = 156156 successfully completed in 49.97 seconds (n_tries = 1).
2026-09-17 18:02:51,151 - INFO - Trying run primary_id = 157157 in region morocco
2026-09-17 18:02:51,152 - INFO - Running AFOLU model

2026-17-Sep 18:02:08.656 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011].
2026-17-Sep 18:02:08.710 Started optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-17-Sep 18:02:51.019 Finished optimizing following years: [1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-09-17 18:02:51,358 - INFO - AFOLU model run successfully completed
2026-09-17 18:02:51,359 - INFO - Running CircularEconomy model
2026-09-17 18:02:51,379 - INFO - CircularEconomy model run successfully completed
2026-09-17 18:02:51,379 - INFO - Running IPPU model
2026-09-17 18:02:51,411 - INFO - IPPU model run successfully completed
2026-09-17 18:02:51,412 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-09-17 18:02:51,420 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-09-17 18:02:51,459 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-09-17 18:02:51,459 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

## Read simulations and check outputs

In [ ]:
# Read input and output files
df_out = ssp.read_output(None)
df_in = ssp.read_input(None)

In [ ]:
def plot_field_stack(
    df,
    fields,
    dict_format,
    time_col="time_period",
    primary_id=0,
    figsize=(18, 8),
    legend_loc='upper right',
    legend_bbox=(1.1, 1),
    ylabel="MT Emissions CO2e",
    xlabel="Time Period",
    title=None,
):
    """
    Plots a stack plot of the selected fields for a given primary_id.

    Args:
        df (pd.DataFrame): DataFrame containing output data.
        fields (list): List of column names to plot.
        dict_format (dict): Formatting dictionary for colors.
        time_col (str): Name of the time column.
        primary_id (int): Value of primary_id to filter.
        figsize (tuple): Figure size.
        legend_loc (str): Legend location.
        legend_bbox (tuple): Legend bbox_to_anchor.
        ylabel (str): Y-axis label.
        xlabel (str): X-axis label.
        title (str): Plot title.
    """
    fig, ax = plt.subplots(figsize=figsize)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    if title:
        ax.set_title(title)

    df_plot = df[df[ssp.key_primary].isin([primary_id])]

    fig, ax = spu.plot_stack(
        df_plot,
        fields,
        dict_formatting=dict_format,
        field_x=time_col,
        figtuple=(fig, ax),
    )

    ax.legend(loc=legend_loc, bbox_to_anchor=legend_bbox, title="Fields")
    plt.show()

In [ ]:
# Define the fields to plot and the formatting dictionary
subsector_emission_fields = matt.get_all_subsector_emission_total_fields()

dict_format = dict(
    (k, {"color": v}) for (k, v) in
    matt.get_subsector_color_map().items()
)

In [ ]:
primary_ids_to_plot = df_out[ssp.key_primary].unique()

In [ ]:
# Plot the emissions stack for the primary_id 0 (which is the baseline)
for primary_id in primary_ids_to_plot:

    plot_field_stack(
        df_out,
        subsector_emission_fields,
        dict_format,
        primary_id=primary_id,
        title=f"Emissions Stack Plot for Primary ID {primary_id}"
    )

# Export Wide File

In [ ]:
all_primaries = sorted(list(df_out[ssp.key_primary].unique()))

# build if unable to simply read the data frame
if df_in is None:
    df_in = []
     
    for region in ssp.regions:
        for primary in all_primaries: 
            df_in_filt = ssp.generate_scenario_database_from_primary_key(primary)
            df_in.append(df_in_filt.get(region))
    
    df_in = pd.concat(df_in, axis = 0).reset_index(drop = True)




df_export = pd.merge(
    df_out,
    df_in,
    how = "left",
)



# check output directory 
dir_pkg = os.path.join(
    ssp.file_struct.dir_out, 
    f"sisepuede_summary_results_run_{ssp.id_fs_safe}"
)
os.makedirs(dir_pkg) if not os.path.exists(dir_pkg) else None


for tab in ["ATTRIBUTE_STRATEGY"]:
    table_df = ssp.database.db.read_table(tab)
    if table_df is not None:
        table_df.to_csv(
            os.path.join(dir_pkg, f"{tab}.csv"),
            index=None,
            encoding="UTF-8"
        )
    else:
        print(f"Warning: Table {tab} returned None.")


df_primary = (
    ssp
    .odpt_primary
    .get_indexing_dataframe(
        sorted(list(df_out[ssp.key_primary].unique()))
    )
)
    
df_primary.to_csv(
    os.path.join(dir_pkg, f"ATTRIBUTE_PRIMARY.csv"),
    index = None,
    encoding = "UTF-8"
)

df_export.to_csv(
    os.path.join(dir_pkg, f"sisepuede_results_{ssp.id_fs_safe}_WIDE_INPUTS_OUTPUTS.csv"),
    index = None,
    encoding = "UTF-8"
)

In [ ]:
# Getting the directory where the outputs are stored
dir_pkg

In [ ]:
RUN_ID_OUTPUT_DIR_PATH = os.path.join(
    RUN_OUTPUT_DIR_PATH, 
    f"sisepuede_results_{ssp.id_fs_safe}"
)

os.makedirs(RUN_ID_OUTPUT_DIR_PATH, exist_ok=True)

df_primary.to_csv(
    os.path.join(RUN_ID_OUTPUT_DIR_PATH, "ATTRIBUTE_PRIMARY.csv"),
    index = None,
    encoding = "UTF-8"
)

df_export.to_csv(
    os.path.join(RUN_ID_OUTPUT_DIR_PATH, f"sisepuede_results_{ssp.id_fs_safe}_WIDE_INPUTS_OUTPUTS.csv"),
    index = None,
    encoding = "UTF-8"
)

for tab in ["ATTRIBUTE_STRATEGY"]:
    table_df = ssp.database.db.read_table(tab)
    if table_df is not None:
        table_df.to_csv(
            os.path.join(RUN_ID_OUTPUT_DIR_PATH, f"{tab}.csv"),
            index=None,
            encoding="UTF-8"
        )
    else:
        logger.warning(f"Warning: Table {tab} returned None.")

In [ ]:
RUN_ID_OUTPUT_DIR_PATH